---
- name: Install packages
  apt:
    update_cache: yes
    pkg:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python3-openssl
      - git
      - nfs-common
      - libopenmpi-dev
      - openmpi-bin
      - zip
      - unzip
      - jq
      - environment-modules
